name: diagpart
description: "Spare parts inventory app for workshop"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  excel: ^4.0.3
  open_file_plus: ^3.4.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
