name: diagpart
description: "Spare parts inventory app for workshop"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  image_picker: any
  path_provider: any
  excel: any
  open_file_plus: any
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
