name: Build APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Patch dependencies
        run: |
          sed -i '/open_file/d' diagpart/pubspec.yaml || true
          echo "" >> diagpart/pubspec.yaml
          echo "dependency_overrides:" >> diagpart/pubspec.yaml
          echo "  path: 1.8.3" >> diagpart/pubspec.yaml

      - name: Fetch dependencies
        run: |
          cd diagpart
          flutter pub get || true

      - name: Build Release APK
        run: |
          cd diagpart
          flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
